on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    env:
      MY_APP_ID: ${{ vars.APP_ID }}
    steps:
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Write Secret to .env
        run: |
          echo "NINJA_API_KEY=${{ secrets.NINJA_API_KEY }}" > .env

      - name: Run Node.js Script
        run: node assets/js/APIhandler.js
