on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    env:
      MY_APP_ID: ${{vars.APP_ID}}
    steps:
      - run: node --version
      - run: npm --version

      - name: Secret Please
        run: echo "My Key Is ${{secrets.NINJA_API_KEY}}"

      - name: Actually use the secret in JS
        run: |
          echo "NINJA_API_KEY=${{ secrets.NINJA_API_KEY }}" > .env
          node APIhandler.js