on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: List files in the repository
        run: ls -R

      - name: Write Secret to .env
        run: echo "NINJA_API_KEY=${{ secrets.NINJA_API_KEY }}" > .env

      - name: Run Node.js Script
        run: node path/to/APIhandler.js
