name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Inject API key into frontend
        run: |
          echo "NINJA=${{ secrets.NINJA_API_KEY }}" >> .env
        env:
          API_KEY: ${{ secrets.NINJA_API_KEY }}
